#!/bin/bash
OUPREFIX="r"
echo "dn: dc=example,dc=com"
echo "objectClass: top"
echo "objectClass: domain"
echo "dc: example"
echo ""
echo "dn: ou=People,dc=example,dc=com"
echo "objectClass: top"
echo "objectClass: organizationalUnit"
echo "ou: People"
echo ""
ouloop=0
while [  $ouloop -lt 10000 ]; do
  echo "dn: ou=$OUPREFIX.$ouloop,dc=example,dc=com"
  echo "objectClass: top"
  echo "objectClass: organizationalUnit"
  echo "ou: $OUPREFIX.$ouloop"
  echo ""
  echo "dn: ou=People,ou=$OUPREFIX.$ouloop,dc=example,dc=com"
  echo "objectClass: top"
  echo "objectClass: organizationalUnit"
  echo "ou: People"
  echo ""
  userloop=0
  while [  $userloop -lt 10000 ]; do
    echo "dn: uid=user.$userloop,ou=People,ou=$OUPREFIX.$ouloop,dc=example,dc=com"
    echo "objectClass: top"
    echo "objectClass: person"
    echo "objectClass: organizationalPerson"
    echo "objectClass: inetOrgPerson"
    echo "uid: user.$userloop"
    echo "cn: user.$userloop $OUPREFIX.$ouloop"
    echo "description: This is the description for User.$userloop of $OUPREFIX.$ouloop."
    echo "employeeNumber: $userloop"
    echo "givenName: user.$userloop"
    echo "homePhone: +1 225 216 5900"
    echo "initials: ASA"
    echo "l: Panama City"
    echo "mail: user.$userloop.$OUPREFIX.$ouloop@example.com"
    echo "mobile: +1 010 154 3228"
    echo "pager: +1 779 041 6341"
    echo "postalAddress: 01251 Chestnut Street,Panama City, DE  50369"
    echo "postalCode: 50369"
    echo "sn: $OUPREFIX.$ouloop"
    echo "st: DE"
    echo "street: 01251 Chestnut Street"
    echo "telephoneNumber: +1 685 622 6202"
    echo "userPassword: {SSHA512}4xxh6vRWM6n3c9tzs5dFqDVC1+6eb1wFjwWCDUX7xCvOnW6EDeEB9WbF9ff/ooZI00mRB8JrJxpb8Nfsz5rOw/pOERlaNHr3"
    echo ""
    let userloop=userloop+1
  done
  let ouloop=ouloop+1
done
